[package]
name = "fatfs"
version = "0.1.0"
authors = ["Rafał Harabień <rafalh1992@o2.pl>"]
repository = "https://github.com/rafalh/rust-fat"
readme = "README.md"
keywords = ["fat", "filesystem"]
categories = ["filesystem"]
license = "MIT"
description = """
FAT filesystem library.
"""

[badges]
travis-ci = { repository = "rafalh/rust-fat" }

[features]
default = ["chrono"]

[dependencies]
byteorder = "1"
bitflags = "1.0"
chrono = { version = "0.4", optional = true }
