[package]
name = "rfat"
version = "0.1.0"
authors = ["Rafał Harabień <rafalh1992@o2.pl>"]

[features]
default = ["chrono"]

[dependencies]
byteorder = "1"
bitflags = "1.0"
chrono = { version = "0.4", optional = true }
